name: Website Uptime Monitor

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch:         # allows manual trigger from GitHub UI

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run uptime check
        run: bash check.sh
