name: Website Uptime Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:       # allow manual trigger

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run uptime check
        run: bash check.sh
